name: Automate Update Copyright Year
on:
  schedule:
    - cron: '0 0 1 1 *'  # Run the action annually on January 1st
  workflow_dispatch:  # Allows for manual trigger

jobs:
  update-copyright-year:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Get Current Year
      id: get_year
      run: |
        # Get the current year using shell commands
        current_year=$(date +%Y)
        echo "CURRENT_YEAR=${current_year}" >> $GITHUB_ENV
        
    - name: Create new branch and commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CURRENT_YEAR: ${{ env.CURRENT_YEAR }}
      run: |
        # Configure Git for the action
        git config --local user.email "Pooya_parsa_dadashi@yahoo.com"
        git config --local user.name "Pooya Parsa Dadashi"
        git config --local user.signingkey 20DDF17D5B973AF5
        git config --local commit.gpgsign true

        
        # Create a new branch for the changes
        BRANCH_NAME="update_copyright_${{ env.CURRENT_YEAR }}"
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        
        git switch -c $BRANCH_NAME develop
        python .github/workflows/update_copyright.py  # Run the Python script
        git add .  # Ensure all changes are added
        git commit -m "docs: update copyright year to ${{ env.CURRENT_YEAR }}"
        git push -f origin $BRANCH_NAME
    
    - name: Create Pull Request Github CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CURRENT_YEAR: ${{ env.CURRENT_YEAR }}
      run: |
        gh pr create --base develop --head datamweb:$BRANCH_NAME --title "docs: update copyright year to ${{ env.CURRENT_YEAR }}" --body "This pull request updates the copyright year to ${{ env.CURRENT_YEAR }}." --label copyright 

      
          



















