name: Automate Update Copyright Year

on:
  schedule:
    - cron: '0 0 1 1 *'  # Run the action annually on January 1st
  workflow_dispatch:  # Allows for manual trigger

jobs:
  update-copyright-year:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run copyright update script
      run: |
        python .github/workflows/update_copyright.py  # Run the Python script

    - name: Create new branch and commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configure Git for the action
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Create a new branch for the changes
        BRANCH_NAME="update-copyright-${{ github.run_id }}"
        
        git switch -c $BRANCH_NAME
        git add .
        git commit -m "Update copyright year to ${current_year}"
        git push origin $BRANCH_NAME

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: $BRANCH_NAME
        title: "docs: update copyright year to ${CURRENT_YEAR}."
        body: "This pull request updates the copyright year to ${CURRENT_YEAR}."
        labels: "automation,copyright,documentation"


















