name: Automate Update Copyright Year

on:
  schedule:
    - cron: '0 0 1 1 *'  # Run the action annually on January 1st
  workflow_dispatch:  # Allows for manual trigger

jobs:
  update-copyright-year:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run copyright update script
      run: |
        python .github/workflows/update_copyright.py  # Run the Python script

    - name: Get Current Year
      id: get_year
      run: |
        # Get the current year using shell commands
        current_year=$(date +%Y)
        echo "CURRENT_YEAR=${current_year}" >> $GITHUB_ENV

    - name: Create new branch and commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CURRENT_YEAR: ${{ env.CURRENT_YEAR }}
      run: |
        # Configure Git for the action
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Create a new branch for the changes
        BRANCH_NAME="update-copyright-${{ env.CURRENT_YEAR }}"
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        
        git switch -c $BRANCH_NAME
        git add .
        git commit -m "Update copyright year to ${{ env.CURRENT_YEAR }}"
        git push origin $BRANCH_NAME

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH_NAME }}
        base: develop
        title: "docs: update copyright year to ${{ env.CURRENT_YEAR }}."
        body: "This pull request updates the copyright year to ${{ env.CURRENT_YEAR }}."
        labels: "automation,copyright,documentation"



















